ARG BASE_TAG=latest
FROM ghcr.io/zshoham/basebox:${BASE_TAG}

RUN pacman -Syyu --noconfirm ninja cmake gdb valgrind clang
RUN source /opt/build.env; curl -fsSL https://tinyurl.com/gef-main -o $XDG_CONFIG_HOME/gdb/gef.py
