ARG BASE_TAG=master
FROM ghcr.io/zshoham/basebox:${BASE_TAG}

RUN pacman -Syyu --noconfirm python-pipx

ENV PIPX_HOME=/opt/pipx
ENV PIPX_BIN_DIR=/usr/local/bin
ENV PYENV_ROOT=/opt/pyenv
ENV PATH=$PATH:$PYENV_ROOT/bin

RUN curl https://pyenv.run | bash
RUN pyenv install 3.8
RUN pipx install pipenv
RUN pipx install poetry

